Добавлены классы для работы с ДО Регистрации бизнеса
skbkontur/extern-java-sdk pull request #191
Opened 2023-11-14 17:33 UTC by AlexVolkow

2023-11-15 14:54 UTC, SvetlanaNesterova requested changes

2023-11-15 14:54 UTC, SvetlanaNesterova commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/descriptions/RegistrationInfo.java
>  public class RegistrationInfo {
Вот этот класс я вообще не поняла. Там же две разные модельки в ДО и билдерах, нельзя одну и ту же использовать с полями вперемешку.

RegistrationInfoDescription, которая возвращается в ДО
https://git.skbkontur.ru/ke-api/ke.api.public/-/blob/master/src/Kontur.Extern.Api.Public.Core.Common/Docflows/Descriptions/BizReg.cs

RegistrationInfo, которая передается в билдер
https://git.skbkontur.ru/ke-api/ke.api.public/-/blob/master/src/Kontur.Extern.Api.Public.Drafts.Models/DraftsBuilders/Meta/Data/BusinessRegistration/RegistrationInfo.cs

2023-11-15 17:01 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/builders/business_registration/BusinessRegistrationDraftsBuilderMetaRequest.java
> +        return DraftsBuilderType.IndividualBusinessRegistration;
Исправил

2023-11-15 17:01 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/builders/business_registration/BusinessRegistrationDraftsBuilderDocumentData.java
> +    private List<Fio> signers;
Исправил

2023-11-15 17:02 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/builders/business_registration/BusinessRegistrationDraftsBuilderData.java
> +    private PaperDocumentsDeliveryType paperDocumentsDeliveryType;
В java нет возможности указать не nullable поле. Все поля nullable

2023-11-15 17:02 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/descriptions/ApplicantCode.java
> +    @SerializedName("р18002")
Добавил

2023-11-15 17:02 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/descriptions/ApplicantCode.java
> +public enum ApplicantCode {
Исправил

2023-11-15 17:02 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/DocumentType.java
> +    BusinessRegistrationIncomingAttachment
Добавил

2023-11-16 12:28 UTC, SvetlanaNesterova commented on extern-api-java-sdk-integrational-tests/src/test/java/ru/kontur/extern_api/sdk/AccountIT.java
> +@Disabled
Ну да, поэтому я и не понимаю, зачем игнорить. Тогда точно никто никогда про них больше не вспомнит)

2023-11-16 12:32 UTC, SvetlanaNesterova commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/builders/business_registration/BusinessRegistrationDraftsBuilderMetaRequest.java
> +        return DraftsBuilderType.IndividualBusinessRegistration;
Сам urn остался старый, `urn:externapi:business-registration:registration` вместо нового `urn:drafts-builder:business-registration`

2023-11-16 12:35 UTC, AlexVolkow commented on extern-api-java-sdk-integrational-tests/src/test/java/ru/kontur/extern_api/sdk/AccountIT.java
> +@Disabled
Ок, вернул

2023-11-16 12:37 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/builders/business_registration/BusinessRegistrationDraftsBuilderMetaRequest.java
> +        return DraftsBuilderType.IndividualBusinessRegistration;
Исправил

2023-11-16 13:06 UTC, SvetlanaNesterova commented
Так, в UlInfo вроде не хватает Orgn (для некоторых форм оно обязательно должно передаваться)

2023-11-16 13:27 UTC, SvetlanaNesterova commented
в ApplicantInfo еще есть поле Email, в ApplicantInfoDescription такого нет. тут не могу сказать, насколько оно необходимо, но неаккуратность в контрактах присутствует

2023-11-16 13:31 UTC, SvetlanaNesterova commented
И еще я бы посоветовала убрать из папки model/descriptions те классы, которые к билдеру относятся. Так как изначально descriptions - это про описания ДО. А классы черновиков/билдеров лежат, получается, на уровень выше просто в model

2023-11-16 17:13 UTC, AlexVolkow commented on extern-api-java-sdk-common/src/main/java/ru/kontur/extern_api/sdk/model/builders/business_registration/BusinessRegistrationDraftsBuilderMetaRequest.java
> +        return DraftsBuilderType.IndividualBusinessRegistration;
А на что влияет этот тип? Мы тестировались на urn:externapi:business-registration:registration.

2023-11-16 17:22 UTC, AlexVolkow commented
> Так, в UlInfo вроде не хватает Orgn (для некоторых форм оно обязательно должно передаваться)

Добавил

2023-11-16 17:22 UTC, AlexVolkow commented
> в ApplicantInfo еще есть поле Email, в ApplicantInfoDescription такого нет. тут не могу сказать, насколько оно необходимо, но неаккуратность в контрактах присутствует)

Добавил

2023-11-16 17:50 UTC, SvetlanaNesterova approved these changes

2023-11-16 18:23 UTC, merged